### ISSUE TITLE
Failing to retrieve temperature from station

### ISSUE THREAD

**Issue by cmamatey** [jshufro/home_assistant_noaa_tides#17]
My attempt to configure a temp sensor is failing with the following error occurring in the logs.

> Logger: custom_components.noaa_tides.sensor
> Source: custom_components/noaa_tides/sensor.py:295
> Integration: noaa_tides
> First occurred: 4:11:06 PM (2 occurrences)
> Last logged: 4:11:07 PM
> 
> Check NOAA Tides and Currents: ('No data was found. This product may not be offered at this station at the requested time.',)

```
sensor:
  - platform: noaa_tides
    name: canal_tide
    station_id: 8726520
    type: tides
    scan_interval: 360
  - platform: noaa_tides
    name: canal_temp
    station_id: 8726520
    type: temp
    scan_interval: 360
```

As far as I can tell, the necessary data should be available: https://tidesandcurrents.noaa.gov/inventory.html?id=8726520

**Comment by jshufro** [comment]
I've added
```yaml
  - platform: noaa_tides
    name: canal_temp
    station_id: 8726520
    type: temp
    scan_interval: 360
```
to my configuration and see 
```
attribution: Data provided by NOAA
temperature: 80.8
temperature_time: '2020-10-21T16:18'
air_temperature: 81.3
air_temperature_time: '2020-10-21T16:18'
unit_of_measurement: °F
friendly_name: canal_temp
device_class: temperature
```
in the home assistant UI for entity `sensor.canal_temp`

I also see some error logging similar to yours, but the sensor is working as expected.
