### ISSUE TITLE
Tide sensor status changing at incorrect time.

### ISSUE THREAD

**Issue by cmamatey** [jshufro/home_assistant_noaa_tides#18]
The status of my tide sensor seems to be changing ~4 hours before the actual tide change.
The configured NOAA station and my Home Assistant service are both located in the eastern time zone where the offset is currently UTC-4.
I am uncertain whether this is a configuration issue or a bug in the code.

![image](https://user-images.githubusercontent.com/5520553/96803343-10c3d580-13da-11eb-98a5-2f223df0b649.png)

```
sensor:
  - platform: noaa_tides
    name: canal_tide
    station_id: 8726520
    type: tides
    scan_interval: 360
```
